formspree_form_id: formspree_form_id
name: Jekflix Name
title: Jekflix | A blog theme for Jekyll Title
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener. Descriptiopn
tags:
  - blog
  - cyber security
  - defense
  - ""
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: admin@digitalcybersafety.com
disqus_username: disqus_username
